#! /bin/sh

xrdb -load ~/.Xresources
sxhkd -c ~/dev/cfg/wm/sxhkdrc &
xbanish &
urxvtd -q -f -o

setvolume 128
setlang usx
(panel & echo $! > /tmp/panel_pid)
(winlangd & echo $! > /tmp/winlangd_pid)

# appearance

setbg
xsetroot -cursor_name left_ptr

# configuration

bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            30

bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config split_ratio           0.52

bspc rule -a Gimp state=floating
bspc rule -a Git-cola state=floating
bspc rule -a fontforge state=floating
bspc rule -a ROX-Filer state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Yad state=floating

bspc rule -a MuPDF state=pseudo_tiled rectangle=794x1123+0+0
bspc rule -a XClock state=pseudo_tiled
bspc rule -a Transmission state=pseudo_tiled

bspc rule -a URxvt:launcher state=floating
bspc rule -a URxvt:sxhkd_hotkeys state=floating
bspc rule -a URxvt:fff state=floating
bspc rule -a URxvt:htop state=pseudo_tiled
