#!/bin/sh

# maild is a daemon for mbsync that syncs account $1 every $2 minutes.
# In addition, it automatically extracts password from PassCmd on
# startup.

# ----------------------------------------------------------------------
# Setup
# ----------------------------------------------------------------------

fifo=~/cfg/mail/mailfifo
mbsyncrc=~/cfg/mail/mbsyncrc
usage="usage: $0 account [minutes]"
passphrase=$RANDOM

err() {
	echo $@ 1>&2
	exit 1
}

# ----------------------------------------------------------------------
# Check arguments
# ----------------------------------------------------------------------

[ $# -lt 1 -o $# -gt 2 -o -z "$1" ] && err $usage
account=$1
if [ -z "$2" ]; then
	minutes=30
else
	[ "$2" -gt 0 ] && minutes=$2 || err $usage
fi

# ----------------------------------------------------------------------
# Replace PassCmd with Pass and store configuration in encrypted file
# ----------------------------------------------------------------------

config=

while read setting value; do
	case "$setting" in
	PassCmd)
		PassCmd=$(printf '%s\n' "$value" | sed -e 's/^"//' -e 's/^+//' -e 's/"$//') # remove quotes and potential plus
		password=$(eval $PassCmd | sed -e 's/"/\"/g') # escape
		config=${config}$(printf '\nPass "%s"\n' "$password")
		;;
	*)
		config=${config}$(printf '\n%s %s\n' "$setting" "$value")
	esac
done < "$mbsyncrc"

# ----------------------------------------------------------------------
# Sync mail every $minutes minutes
# ----------------------------------------------------------------------

sync() {
	printf '(%s)\n' $(date +%H:%M)

	[ -e "$fifo" ] && err '$fifo already exists'
	mkfifo "$fifo"
	mbsync -c "$fifo" "$account" &
	printf '%s\n' "$config" > "$fifo"
	rm "$fifo"
}

while true; do
	sync
	sleep $((minutes * 60))
done
