#!/bin/sh

fifo=~/cfg/wm/windowmaker/wminfo/sysmon_fifo
pidfifo=~/cfg/wm/windowmaker/wminfo/sysmon_pidfifo

err() {
	printf '%s\n' "$@" 1>&2
	exit 1
}

on_exit() {
	rm "$fifo" "$pidfifo"
	cat "$pidfifo" | while read pid; do kill $pid; done
}

[ -e "$fifo" ] && err "$fifo already exists"
mkfifo "$fifo"
trap 'on_exit 2> /dev/null' INT TERM QUIT EXIT

# Battery

while true; do
	printf 'B:%s%%\n' $(apm -l)
	sleep 30
done > "$fifo" & echo $! > "$pidfifo" &

# Keyboard layout

watch -i /tmp/keyboard_layout | while read file; do
	printf 'L:%s\n' $(cat $file)
done > "$fifo" & echo $! > "$pidfifo" &

# Main loop

B=
L=
while IFS=: read key value; do
	case $key in
	B) B=$value ;;
	L) L=$value ;;
	esac

	echo "$B"
	echo "$L"
done < "$fifo"
