#!/bin/sh

xset fp+ /usr/local/share/fonts/terminus
xset fp+ /usr/local/share/fonts/mscorefonts

export LC_CTYPE=en_US.UTF-8

setxkbmap usx

sensitivity 1.0
xset m 2 0 # smooth acceleration

mixerctl inputs.mix_beep=0 # lowest beep volume

xmodmap -e "pointer = 1 2 3 6 7 10 11 4 5 8 9 12 13 14 15 16"
xinput set-prop /dev/wsmouse0 "WS Pointer Wheel Emulation" 1
xinput set-prop /dev/wsmouse0 "WS Pointer Wheel Emulation Button" 2
xinput set-prop /dev/wsmouse0 "WS Pointer Wheel Emulation Axes" 4 5 8 9

if [ -x /usr/local/bin/dbus-launch -a -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
        eval `dbus-launch --sh-syntax --exit-with-x11`
fi

# run start script when ready:
while true; do
	if [ -z "$DISPLAY" ]; then
		sleep 0.5
	else
		~/cfg/wm/start
		break
	fi
done &

exec wmaker
