#!/bin/sh

xset fp+ /usr/local/share/fonts/mscorefonts
xset fp+ /usr/local/share/fonts/ghostscript
xset fp+ /usr/local/share/fonts/terminus
xset fp+ /usr/local/share/fonts/leggie
xset fp+ /home/john/dev/fonts/tewi-font/out
xset fp+ /home/john/dev/fonts/luculent
xset fp+ /home/john/dev/fonts/tamsyn-font

export LC_CTYPE=en_US.UTF-8

setxkbmap usx

sensitivity 0.5
xset m 3/1 3

# weird mouse setup
xmodmap -e "pointer = 1 3 2 6 7 10 11 4 5 8 9 12 13 14 15 16"
xinput set-prop /dev/wsmouse "WS Pointer Wheel Emulation" 1
xinput set-prop /dev/wsmouse "WS Pointer Wheel Emulation Button" 3
xinput set-prop /dev/wsmouse "WS Pointer Wheel Emulation Axes" 4 5 8 9

# for trash can to work
if [ -x /usr/local/bin/dbus-launch -a -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
	eval $(dbus-launch --sh-syntax --exit-with-x11)
fi

exec bspwm -c /home/john/dev/config/wm/bspwmrc
