#!/bin/sh

xset fp+ /usr/local/share/fonts/mscorefonts
xset fp+ /usr/local/share/fonts/ghostscript
xset fp+ /usr/local/share/fonts/terminus

export LC_CTYPE=en_US.UTF-8

setxkbmap usx
xmodmap -e "pointer = 1 2 3 8 9 10 11 4 5 6 7 12 13 14 15 16"
xset m 1/1 1 # acceleration

# for trash can to work
if [ -x /usr/local/bin/dbus-launch -a -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
	eval $(dbus-launch --sh-syntax --exit-with-x11)
fi

wmaker
