#! /bin/sh

xrdb -load /home/john/.Xresources
sxhkd -c /home/john/dev/config/wm/sxhkdrc &
xbanish &
urxvtd -q -f -o

xsetroot -cursor_name left_ptr

if [ -e /home/john/.bg ]; then
	xsetroot -solid $(tail -1 /home/john/.bg)
fi

bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            32

bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config split_ratio           0.52

bspc rule -a Gimp state=floating follow=on
bspc rule -a ROX-Filer state=floating
bspc rule -a MuPDF state=pseudo_tiled rectangle=794x1123+0+0
bspc rule -a XClock state=pseudo_tiled

bspc rule -a URxvt:launcher state=floating
bspc rule -a URxvt:sxhkd_hotkeys state=floating
