#! /bin/sh

xrdb -load /home/john/.Xresources
sxhkd -c /home/john/dev/config/wm/sxhkdrc &
xbanish &
urxvtd -q -f -o

/home/john/bin/setvolume 128
/home/john/bin/setlang us
/home/john/bin/panel & echo $! > /tmp/panel_pid
/home/john/bin/winlangd & echo $! > /tmp/winlangd_pid

# appearance

xsetroot -cursor_name left_ptr
/home/john/bin/randombg

# configuration

bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            32

bspc config focus_follows_pointer true
bspc config single_monocle        false
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config split_ratio           0.52

bspc rule -a Gimp state=floating
bspc rule -a Git-cola state=floating
bspc rule -a fontforge state=floating
bspc rule -a ROX-Filer state=floating
bspc rule -a Xarchiver state=floating
bspc rule -a Yad state=floating

bspc rule -a MuPDF state=pseudo_tiled rectangle=794x1123+0+0
bspc rule -a XClock state=pseudo_tiled

bspc rule -a URxvt:launcher state=floating
bspc rule -a URxvt:sxhkd_hotkeys state=floating
