#!/bin/sh

cat /tmp/exit-with-wm |
while read pid; do
	ps -o pgid -p $pid | nth 2 # get process group id
done |
while read pgid; do
	kill -TERM -$pgid # kill all processes within group
done

rm /tmp/exit-with-wm
