#!/bin/sh

# watch battery life and warn at certain levels

warn() { notify-send -u "$1" 'Battery low' ${BATTERY}%; }
err() { echo "$@" 1 >& 2; exit 1; }

while BATTERY=$(apm -l); do
	ps -cax | grep ' dunst$' 1>&- || err "$0: dunst not running"
	if [ "$(apm -a)" -eq 0 ]; then # if not charging
		case "$BATTERY" in
			10) warn normal ;;
			5) warn critical ;;
		esac
	fi
	sleep 30
done
