#!/bin/sh

default=usx
set=setxkbmap

[ -d /tmp/winlangs ] && rm -r /tmp/winlangs
mkdir -p /tmp/winlangs

last=$(pfw)
while true; do
	new=$(pfw)
	if [ "$new" != "$last" ]; then
		echo "old: $last, new: $new"
		if [ -e /tmp/winlangs/$new ]; then
			$set $(cat /tmp/winlangs/$new)
		else
			$set $default
		fi
		last=$new
	fi
	sleep 0.2
done
